### ISSUE TITLE
如果汉字之间有空格,转换以后空格会变成叹号

### ISSUE THREAD

**Issue by mike8625** [aui/font-spider#102]
如果汉字之间有空格,转换以后空格会变成叹号,转换了好几个字体都这样...

**Comment by songlipeng2003** [comment]
一样的问题

**Comment by gqbre** [comment]
同，空格变感叹号

**Comment by songlipeng2003** [comment]
master分支已经解决

**Comment by gy134340** [comment]
。。

**Comment by gy134340** [comment]
好像npm install现在的版本仍有问题

**Comment by gy134340** [comment]
还有原来的字体备份在哪里？

**Comment by songlipeng2003** [comment]
@gy134340 那个应该不是最新版本。我fix后，IE下还是有问题。就是换行的时候还是会替换成感叹号。目前找到的解决方法是删除一个字符。第一个为空的字符，显示为了！。用字符编辑工具删除它就好了.
我使用的 http://font.baidu.com/editor/

**Comment by gy134340** [comment]
谢谢，找到了笨方法，写在span标签然后在外面加class。
``<h3><span class="cn">红点奖</span>&nbsp<span class="m_after cn">(Red</span>&nbsp<span class="m_after cn"> Dot</span>&nbsp<span class="cn">Award)</span></h3>'''

**Comment by songlipeng2003** [comment]
@gy134340 这样太麻烦了。不值当

**Comment by chenfengyanyu** [comment]
遇到同样问题，@songlipeng2003 方案不错，谢谢～

**Comment by songlipeng2003** [comment]
@chenfengyanyu 不客气，我一直在看能不能直接解决，不用每次编辑。不过看了 fontmin 和 font-spider没有找到特别能修改解决的地方，不过我感觉还是 fontmin的问题

**Comment by GeeBar** [comment]
同样有空格。英文间的空格也是显示！的。目前使用的gulp插件，用字符编辑工具的话，完全无法自动化了。。。

**Comment by songlipeng2003** [comment]
@GeeBar 所有浏览器?还是IE？

**Comment by junmer** [comment]
看来这个问题 大家比较通用 我升级一下 fontmin 吧 默认加一下空格

> https://github.com/ecomfe/fontmin/issues/39

**Comment by gy134340** [comment]
早说两天项目不至于撤掉这个插件

**Comment by aui** [comment]
已经解决

**Comment by yolo2013** [comment]
1.3.3依然还有这个问题
