### ISSUE TITLE
转换中文字体无效果

### ISSUE THREAD

**Issue by DasonCheng** [aui/font-spider#103]
## 字体效果
![image](https://cloud.githubusercontent.com/assets/16243342/17695085/90b2e296-63d9-11e6-96e4-8d55856cc903.png)

## 操作结果
![image](https://cloud.githubusercontent.com/assets/16243342/17692218/4ede98b4-63cb-11e6-91d8-aa3a1a933950.png)

**Comment by aui** [comment]
“这是测试时的效果，中文并不是对应的字体，字母却变了” ——不太明白，希望提供 demo

**Comment by DasonCheng** [comment]
https://github.com/DasonCheng/font-test

**Comment by DasonCheng** [comment]
https://github.com/DasonCheng/font-test

**Comment by junmer** [comment]
```
not support cmap format 2
```

这个 格式的字体 是没有 unicode map 的， 尚不支持

**Comment by DasonCheng** [comment]
请问目前可以支持那些字体

**Comment by junmer** [comment]
<https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html>

cmap format 4，可以联系字体厂商给个新一点的字体

**Comment by DasonCheng** [comment]
### 如果找到了解决方案请告诉我一下，另外我用其他的字体压缩工具操作成功了

![image](https://cloud.githubusercontent.com/assets/16243342/17695009/3ca02556-63d9-11e6-95c6-9fc9eaad4b2f.png)

**Comment by junmer** [comment]
请教 其他的压缩工具是？

**Comment by DasonCheng** [comment]
刚重新比对测试了一下，两个工具结果相同。原理应该是一样的，根据编码表精简字体，所以格式不支持就会出错，例如昨天遇到的问题
```
not support cmap format 2
```
另外一个工具是   fontmin   ，对于昨天的测试失误表示歉意！👀
