### ISSUE TITLE
总是找不到web font 

### ISSUE THREAD

**Issue by aqnaruto** [aui/font-spider#111]
![image](https://cloud.githubusercontent.com/assets/9067159/19513126/7114e266-9621-11e6-98f4-df0a0af3a93d.png)
如图，字体文件是有的 但是找不到。

**Comment by aui** [comment]
可以提供这个 HTML 吗？

**Comment by aqnaruto** [comment]
不好意思 可以把我删掉。我的失误

**Comment by sumaolin** [comment]
遇到一样的问题，是什么原因？ @aqnaruto
