### ISSUE TITLE
无法压缩loading 

### ISSUE THREAD

**Issue by MicroJes** [aui/font-spider#114]
run font-spider 显示loading 就完了 

debug info 信息显示如下

[
![f1](https://cloud.githubusercontent.com/assets/14371617/21284235/f167ed66-c450-11e6-9536-04596068e1d4.PNG)
![f2](https://cloud.githubusercontent.com/assets/14371617/21284236/f16905de-c450-11e6-8396-907385bd0e80.PNG)

](url)

**Comment by MicroJes** [comment]
font-spider 版本信息3.8.0

**Comment by aui** [comment]
``--info`` 它只显示信息不压缩，文档与 ``font-spider --help`` 均有说明。
