### ISSUE TITLE
压缩字体时控制台报错

### ISSUE THREAD

**Issue by jyy12** [aui/font-spider#12]
**用test目录下index.html压缩字体，报如下错误：**
C:\Users\Xiao106347\Desktop\font-spider-master\test>font-spider index.html
Error: C:\Users\Xiao106347\Desktop\font-spider-master\test\css\g2.css
Error: missing '}' near line 1:13

Error: C:\Users\Xiao106347\Desktop\font-spider-master\test\css\ui.css:6
Error: not found "404.css"

Error: C:\Users\Xiao106347\Desktop\font-spider-master\test\css\ui.css:7
Error: not found "/css/http.css"

Error: C:\Users\Xiao106347\Desktop\font-spider-master\test\css\ui.css:8
Error: does not support the absolute path "http://test.com/css/test.css"

Font name: art
Original size: 1981.852 KBFont name: ft
Original size: 2736.004 KBFont name: S13T
Original size: 5286.144 KB
events.js:72
   throw er; // Unhandled 'error' event
    ^
Error: write EIO
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

**使用微软雅黑报如下错误：**
C:\Users\Xiao106347\Desktop\font>font-spider demo.html
Font name: bai
Original size: 15043.584 KB
events.js:72
   throw er; // Unhandled 'error' event
    ^
Error: write EIO
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

**使用新唐人简篆体报如下错误，这个的报错是因为字体不支持的原因吗：**
C:\Users\Xiao106347\Desktop\font>font-spider demo.html
Optimizer error.
C:\Users\Xiao106347\Desktop\font\bai.ttf
Uses unrecognised table 'mort'

**Comment by aui** [comment]
1. test 目录故意编写了各种错误的例子
2. 目前字蛛有一些字体数据不能解析，支持较好的是方正字库

**Comment by jyy12** [comment]
events.js:72
throw er; // Unhandled 'error' event
^
Error: write EIO
at errnoException (net.js:901:11)
at Object.afterWrite (net.js:718:19)
请问这个报错的原因是什么，目录下的字体文件是有生成的

**Comment by ttwa** [comment]
报错，不是正规字体，出现错误。

下个版本什么发布呢？

**Comment by aui** [comment]
新版已经更换了压缩模块，再试试？

**Comment by zuibunan** [comment]
![image](https://cloud.githubusercontent.com/assets/3386786/11441926/bd6ea390-954b-11e5-91a9-d074e57d70bd.png)

思源黑体

**Comment by aui** [comment]
@zuibunan 发一个新 issues 吧
