### ISSUE TITLE
无法检索JS控件中的文字？

### ISSUE THREAD

**Issue by nicholaelaw** [aui/font-spider#127]
用[plotly](https://plot.ly)制作的图表，纯客户端JS对象，静态页面。

压缩前：
![image](https://cloud.githubusercontent.com/assets/10719482/26093018/7af6857c-3a46-11e7-8a27-c91c607f1f15.png)

压缩后：
![image](https://cloud.githubusercontent.com/assets/10719482/26093029/878b638e-3a46-11e7-94eb-f1dd4764642e.png)

出问题的html元素：

    <text class="legendtext user-select-none" x="40" y="4.680000000000001" data-unformatted="通过率" 
    style="text-anchor: start; font-family: monospace-zh; font-size: 12px; fill: rgb(68, 68, 68); fill-opacity: 1; white-space: pre; 
    visibility: inherit;" data-bb="410">通过率</text>

`monospace-zh`定义：

    @font-face {
      font-family: "monospace-zh";
      src: url("fonts-zh/NotoSansMonoCJKsc-Regular.eot?") format("embedded-opentype"), 
      url("fonts-zh/NotoSansMonoCJKsc-Regular.woff2") format("woff2"), 
      url("fonts-zh/NotoSansMonoCJKsc-Regular.woff") format("woff"), 
      url("fonts-zh/NotoSansMonoCJKsc-Regular.ttf") format("truetype"), 
      url("fonts-zh/NotoSansMonoCJKsc-Regular.svg#monospace-zh") format("svg");
      font-style: normal;
      font-weight: normal; 
    }

等有空我写个demo传上来。

**Comment by aui** [comment]
字蜘和搜索引擎一样，它是不支持 javascript 动态内容的：<https://github.com/aui/font-spider/blob/master/README-ZH-CN.md#限制>

**Comment by nicholaelaw** [comment]
顺便提一句，我的解决办法是单独写一个页面，把可能会出现的字符统统写进去。前提是能控制JS生成的内容。
