### ISSUE TITLE
如何在node环境下采用js函数而不是命令行的方式来执行呢？

### ISSUE THREAD

**Issue by Hades-li** [aui/font-spider#142]
我想将其开发成一个客户端工具，之前采用的是exec调用命令行的方式来执行gulp。但这种方式只能在本地调试，而无法打包发布，因为gulp必须要全局安装，才能执行命令。所以只能希望直接采用js函数的方式来调用，还请指点。

**Comment by aui** [comment]
1. 如果是希望以 js api 调用 font-spider，你应该阅读 api 文档
2. 如果希望以 js api 调用 gulp，而非全局调用，你应该阅读 gulp

**Comment by Hades-li** [comment]
抱歉，已经看到api了。目前遇到的问题是，貌似是font-spider经过webpack打包后会报错。我采用了electron-vue的一个框架，在这个框架中，仅require('font-spider')运行时就会报错。我正在验证是否是由于webpack打包造成。
