### ISSUE TITLE
font-spider安装错误

### ISSUE THREAD

**Issue by JoinChang** [aui/font-spider#152]
npm install font-spider -g
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
C:\Users\joinc\AppData\Roaming\npm\font-spider -> C:\Users\joinc\AppData\Roaming\npm\node_modules\font-spider\bin\font-spider

> ttf2woff2@2.0.3 install C:\Users\joinc\AppData\Roaming\npm\node_modules\font-spider\node_modules\ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\joinc\AppData\Roaming\npm\node_modules\font-spider\node_modules\ttf2woff2
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
+ font-spider@1.3.4
added 523 packages in 115.889s

**Comment by aui** [comment]
按照它错误提示尝试解决？
```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

```
