### ISSUE TITLE
安装的时候报错

### ISSUE THREAD

**Issue by slj20** [aui/font-spider#156]
$ npm install font-spider -g
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "font-spider" "-g"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 no such package available : @gulp-sourcemaps/map-sources
npm ERR! 404
npm ERR! 404  '@gulp-sourcemaps/map-sources' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\git\gulp-font-spider\npm-debug.log

**Comment by aui** [comment]
可能和你网络环境有关系。如果不能解决问题，建议你去 npm 这个项目提 issues
