### ISSUE TITLE
在新版本的node下面执行font-spider xxx.html会报错

### ISSUE THREAD

**Issue by wonsikin** [aui/font-spider#16]
* 操作系统版本：MAC OS Yosemite
* NodeJS版本: v0.12.0
* 报错信息： 

    Error: /Users/felix/Downloads/text/html/fs.html
    Error: syntax error

**Comment by lanson647** [comment]
同求原因，我也遇到相同问题~

**Comment by aui** [comment]
HTML 解析失败，说明页面有问题。请提供源文件，才能有助于解决问题。

**Comment by wonsikin** [comment]
有一台mac笔记本，node版本是0.10.30的，同样的文件能压缩成功

**Comment by aui** [comment]
确认与最新版本 Nodejs 出现兼容问题，正在解决中。如果急需使用，可以使用 NodeJS v0.10.21

**Comment by turingou** [comment]
可以在 `package.json` 中指定一下 `{ "engines" : { "node" : "<=0.10.21" } }`

**Comment by aui** [comment]
已经修复最新版本不兼容的问题
