### ISSUE TITLE
Windows 8.1 x64，安装了Perl环境还是无法识别font-spider命令

### ISSUE THREAD

**Issue by tonghuashuo** [aui/font-spider#17]
我在 linux 上安装使用正常的，到 Windows 下总是识别不到 font-spider 命令。
用 npm 安装的，能 require 到。Perl 也装了，PATH配好，helloworld通过，环境应该是对了。
但执行font-spider命令始终提示“不是内部或外部命令”，不知怎么办。

求教，是我哪里方法不对吗？（Win8.1 x64）

**Comment by aui** [comment]
这种问题很难排查，因为你根本没有给出任何有助于解决问题的信息，比如安装命令行、配置等。

**Comment by aui** [comment]
难道是没有安装在全局造成的？安装的时候是否是使用了`-g`参数？

**Comment by tonghuashuo** [comment]
cmd管理员运行，命令如下：
>npm install font-spider -g

![require](https://cloud.githubusercontent.com/assets/6594276/6507304/147728c0-c38c-11e4-9976-d6d123136348.png)

Perl用的Strawberry，5.20.2的版本
![perl](https://cloud.githubusercontent.com/assets/6594276/6507296/0b256160-c38c-11e4-9e29-2aaf0d97575b.png)

font-spider目录下内容：
![fontspider](https://cloud.githubusercontent.com/assets/6594276/6507311/292f306e-c38c-11e4-93bf-be7dae96822e.png)

**Comment by tonghuashuo** [comment]
现在运行就是这样
![err](https://cloud.githubusercontent.com/assets/6594276/6507425/ea404658-c38c-11e4-9ccd-91124a0a4bdc.png)

node和perl都配置过环境变量了，font-spider需要单独配置环境变量吗？linux下用得很顺利，装好就能用了，换到Windows下才遇到的问题。

**Comment by miniMofish** [comment]
你perl没安装对吧？我安装的ActivePerl，完全OK

**Comment by aui** [comment]
可能需要重启
