### ISSUE TITLE
关于css文件路径问题

### ISSUE THREAD

**Issue by miniMofish** [aui/font-spider#20]
请问font-spider不支持css文件是绝对路径引入的么？
![1](https://cloud.githubusercontent.com/assets/3241196/6802291/1abed7b8-d26a-11e4-8b71-650aec9b8a21.png)

把css文件换成相对路径引用就可以了。
如果不支持的话，后续会支持吗？

**Comment by aui** [comment]
最新版现在支持了。因为字体要被压缩处理，所以字体必须是本地可访问的文件，可以使用map参数将线上路径映射到本地来
