### ISSUE TITLE
font-spider has error when compress the html file

### ISSUE THREAD

**Issue by startheart** [aui/font-spider#21]
The Command line report ERROR when executing command 'font-spider test.html' in Win7 system.
The report contents are as follows:ERROR TypeError:
 Cannot read property 'contours' of undefined at C:\Users\DELL\AppData\Roaming\npm\node_modules\font-spider\node_modules\fontmin\node_modules\fonteditor-ttf\lib\ttf\table\OS2.js:156:59. 
I think it's a compatibility problem about Win7!
![Uploading error1.png . . .]()
![Uploading error2.png . . .]()

**Comment by aui** [comment]
能否提供字体相关信息？

**Comment by startheart** [comment]
已经找出错误的原因了，是因为压缩不了兰亭超细黑字体

**Comment by aui** [comment]
@junmer
