### ISSUE TITLE
转换的字体在某些浏览器中显示不全

### ISSUE THREAD

**Issue by 17leba** [aui/font-spider#23]
![image](https://cloud.githubusercontent.com/assets/3077512/7083000/c5c18972-df8e-11e4-9e00-bf8ad3ab53c8.png)
是字体库的原因还是浏览器的原因呢？

**Comment by aui** [comment]
IE 浏览器？具体版本是？

**Comment by 17leba** [comment]
IE8
只是部分字体显示不正常，会缺失一部分！

**Comment by aui** [comment]
ie8使用的是 eot 格式。你说的是说生成的字体缺乏字形么？

**Comment by 17leba** [comment]
pinghei-light字体。
而且在360极速模式下面也出现显示不全的问题。
![image](https://cloud.githubusercontent.com/assets/3077512/7114258/581e7696-e20e-11e4-872e-bbf196de7557.png)

我测试了一下，这是正常的14px字号：
![image](https://cloud.githubusercontent.com/assets/3077512/7114183/c1ba61c4-e20d-11e4-80f6-9d80a7926358.png)
会出现文字显示不全的情况。

可是缩放浏览器到一定程度就显示完整了：
![image](https://cloud.githubusercontent.com/assets/3077512/7114210/f610bc16-e20d-11e4-8faa-dd2935a494c7.png)
上面是缩放135%的情况下，显示完全。

而且更改字体大小也会显示完全，改为20px的情况：
![image](https://cloud.githubusercontent.com/assets/3077512/7114244/3823c15c-e20e-11e4-8fff-c7eb94b1177b.png)
![image](https://cloud.githubusercontent.com/assets/3077512/7114247/39d633ae-e20e-11e4-8785-9831acfa40a4.png)

如上，IE放大屏幕或者字号也显示完全了。
所以生成的字体库应该没问题。

问题应该还是出在浏览器对字体的渲染上面吧：
火狐的低版本（4.0beta）和高版本都没有问题，windows上面的Safari显示不全，360极速浏览器（webkit内核）显示不全，IE显示不全，chrome浏览器40.0.2214.94 m版本没有问题。
 
但是问题具体出现的原因还是不能确定。

**Comment by aui** [comment]
<http://stackoverflow.com/questions/4112125/font-face-alias-issues-on-pc>

**Comment by junmer** [comment]
@aui   [fontmin](github.com/ecomfe/fontmin) 更新了 `0.7.3` 增加了 `hinting` ，请更新试试看 :smiley:

**Comment by aui** [comment]
已经更新 :)

**Comment by 17leba** [comment]
多谢

**Comment by lomotony** [comment]
@aui 请问这个问题修了吗？

**Comment by lomotony** [comment]
@17leba 你这个问题解决了吗？

**Comment by lomotony** [comment]
@aui ?
