### ISSUE TITLE
是不是只能压缩静态的文字？

### ISSUE THREAD

**Issue by Voyga** [aui/font-spider#24]
我要压缩的这个app文字全是动态的，有解决办法么？

**Comment by aui** [comment]
推荐使用有字库等在线服务。
字蛛也将会提供 CDN 动态压缩解决方案。

**Comment by Jerry-Lau** [comment]
使用有字库压缩动态文字不成功，很蛋疼。

**Comment by aui** [comment]
已经发布 v0.3.0 版本，API 文档有压缩动态页面的示例，不过需要部署到字体所在的服务器，业务层部分可能还需要自己封装下。
