### ISSUE TITLE
其余字体格式没有生成的问题

### ISSUE THREAD

**Issue by rguanghui** [aui/font-spider#3]
@aui 有错误，不知哪里的问题。新 Issues :walking: :walking: :walking: 

![qq 20141224101420](https://cloud.githubusercontent.com/assets/3411958/5545174/b4c587f0-8b55-11e4-8469-27940b811ed8.png)
![qq 20141224101619](https://cloud.githubusercontent.com/assets/3411958/5545188/e936a3a2-8b55-11e4-8ce9-c01cc319d302.png)
![qq 20141224101611](https://cloud.githubusercontent.com/assets/3411958/5545190/ed5c7952-8b55-11e4-9a5d-3acbe2312089.png)

**Comment by hezaizai** [comment]
华康翩翩字体压缩不成功   显示not created 是怎么回事啊？
