### ISSUE TITLE
发现个问题，我用思源字体 转换出来的字体用不了

### ISSUE THREAD

**Issue by minjiex** [aui/font-spider#4]
![image](https://cloud.githubusercontent.com/assets/7919769/5575539/bd38e0d4-901a-11e4-91e5-34ccd23fe1ee.png)
![image](https://cloud.githubusercontent.com/assets/7919769/5575541/e1ddbd74-901a-11e4-9380-920b06609189.png)
![image](https://cloud.githubusercontent.com/assets/7919769/5575575/9d1d6530-901b-11e4-8c8b-e03cd3d780d1.png)

有解决办法吗？

**Comment by junmer** [comment]
现在的压缩模块，应该可以支持思源 ttf 了，可以点 [这里](http://ecomfe.github.io/fontmin) 看效果，下载 [思源 ttf ](http://yun.baidu.com/s/1gdrMurh)

**Comment by Jerry-Lau** [comment]
这个和有字库(www.youziku.com)里面提供的方法是不是一样的？

**Comment by minjiex** [comment]
赞一个先！我明天再试试看
