### ISSUE TITLE
font-spider 加载css报错

### ISSUE THREAD

**Issue by luxueyan** [aui/font-spider#40]
font-spider app/index.html
Error: ENOENT, load "/bower_components/fontawesome/css/font-awesome.css" failed: ENOENT, open '/bower_components/fontawesome/css/font-awesome.css'
    at /usr/local/lib/node_modules/font-spider/src/spider/resource.js:174:18
    at /usr/local/lib/node_modules/font-spider/node_modules/promise/lib/core.js:33:15
    at flush (/usr/local/lib/node_modules/font-spider/node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:419:13)

**Comment by luxueyan** [comment]
看源码找到问题了，希望文档可以完善，html中 <base href="xxx"/> 的设置 会影响css的路径解析，
map参数是支持正则的，没有说明，所以解决方案是设置了map参数
map: [['/styles/(.*).css', __dirname + '/dist/styles/$1.css']]

**Comment by aui** [comment]
`<base>` 标签是 HTML 定义的规则，font-spider 做了基本支持。文档我在下一版本中补上
