### ISSUE TITLE
如何支持使用jade或者hbs进行渲染的页面

### ISSUE THREAD

**Issue by yeelan0319** [aui/font-spider#42]
我使用字蛛对我的页面进行处理的时候，出现如下错误
```
$ font-spider views/*.hbs
Loading ..<web font not found>
```

请问是因为字蛛不能够支持使用jade或者hbs进行渲染的页面？
目前我的网页是使用include引入header和footer，通过express对我的partial的hbs在后台进行渲染。所以在一开始字蛛进行处理的时候并没有完整的html页面。

谢谢！

**Comment by aui** [comment]
请看文档的说明，必须是 HTML，且包含 CSS。未来考虑支持模板片段（但也必须是标准 HTML）

**Comment by yeelan0319** [comment]
@aui 谢谢糖饼

那现在是必须生成临时的html文件吗？请问一般大家都是如何处理的呢？

另外我在使用的时候还遇到了另外一个错误，不知道是否有人遇到过类似的问题？
```
Load: /webportal/public/stylesheets/jquery-ui.min.css
Load: /webportal/public/stylesheets/jquery-ui.min.css
Error: Promise is not defined
    at stream (/usr/local/lib/node_modules/font-spider/bin/font-spider:125:16)
    at /usr/local/lib/node_modules/font-spider/node_modules/promise/lib/core.js:33:15
    at flush (/usr/local/lib/node_modules/font-spider/node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:442:13)
```

**Comment by yeelan0319** [comment]
我大概知道了，发现电脑上的node version是0.10.32。估计升级到0.12可以解决这个ES6新特性的问题。

谢谢字蛛团队，非常喜欢这个针对汉字的实现方法，不知道是否有可以参与贡献的地方？

**Comment by aui** [comment]
刚更新了版本兼容了 < 0.12 的 Nodejs 版本。

字蛛正在尝试做服务端动态压缩方案，欢迎参与

**Comment by evolutionjay** [comment]
@aui  请问服务器动态渲染出了吗
