### ISSUE TITLE
与字体图标iconfont有冲突

### ISSUE THREAD

**Issue by up2day** [aui/font-spider#49]
我做的页面使用字体图标iconfont在先，然后加入字蛛字体。
问题描述：运行完字蛛字体压缩以后，原有的iconfont字体全部无效，排查后发现是iconfont的css文件被修改了，虽然可以手动改正这个bug，但觉得有必要提出来，希望字蛛越做越好~

**Comment by aui** [comment]
字蛛不会去修改 css 的文件，可以排查下是否是其他原因

**Comment by up2day** [comment]
![20150916105205](https://cloud.githubusercontent.com/assets/10770421/9895395/9c108f9c-5c61-11e5-995b-56fcf94043c7.jpg)
![20150916105044](https://cloud.githubusercontent.com/assets/10770421/9895396/9c113c9e-5c61-11e5-81a0-a4b7d0595086.jpg)
![20150916104902](https://cloud.githubusercontent.com/assets/10770421/9895397/9c119806-5c61-11e5-9738-4fea923f8718.jpg)
![20150916104831](https://cloud.githubusercontent.com/assets/10770421/9895398/9c19a884-5c61-11e5-8b6e-2b3c6a019556.jpg)
我之前说错了，被修改的不是iconfont的css文件，而是iconfont的字体文件，我用旧的iconfont字体文件覆盖上去就好了。
我用不同的字体，反复复做了几次都是这样的结果。

**Comment by aui** [comment]
可以使用 `--ignore` 参数来忽略某个字体：

```ssh
font-spider --ignore iconfont.* index.html 
```

正在解决图标字体伪元素的 `content` 属性支持的问题
