### ISSUE TITLE
grunt里的路径配置

### ISSUE THREAD

**Issue by miniMofish** [aui/font-spider#5]
有些配置路径会出现错误提示：Fatal error: [object Object]
不知为什么…
比如：src: ['shop/**/*.{html,shtml,htm}'] 这样子可以跑成功
但：src: ['page/**/*.{html,shtml,htm}'] 这样子就失败了
都是存在的目录并且也不为空，里面的目录结构也差不多一样
求解疑

**Comment by aui** [comment]
gruntjs 与 font-spider 都是采用 glob 来解析通配符路径，glob 文档：<https://github.com/isaacs/node-glob>

**Comment by aui** [comment]
另外，font-spider 不支持非静态文件，比如里面包含服务端语句的页面，可能导致解析出错。

**Comment by miniMofish** [comment]
已找到问题，JS代码不能写在 /html 后面~
