### ISSUE TITLE
找到数个关于 --ignore 和 font-face 处理的 bug，内详

### ISSUE THREAD

**Issue by starkshaw** [aui/font-spider#52]
我个人近期频繁使用 font-spider，对其对静态页面的处理效果非常满意，但是仍然有一些 bug 或者是我理解不到位，在此提出：

- `--ignore` 参数不起作用  
当我期望将一个文件夹中所有的 CSS 都忽略时，我使用类似 `font-spider ./index.html ./zh_cn/index.html --ignore /Documents/assets/css/*.css,/Documents/assets/plugins/font-awesome/css/*.css` 的命令（上述目录结构为了隐私做了修改）却提示找不到 `/Documents/assets/css/*.css,/Documents/assets/plugins/font-awesome/css/*.css` 然而我使用的是绝对路径所以理应找得到——抑或是我使用的语法有问题？

- `font-face` 对同一字族不同字重的字体无法处理  
假设我在 CSS 中有如下代码：
```
/* Embedding fonts */
@font-face {
    font-family: "KaiGenGothic";
    font-weight: bold;
    src: url('../../assets/fonts/KaiGenGothicCN-Bold.ttf');
}

@font-face {
    font-family: "KaiGenGothic";
    font-weight: normal;
    src: url('../../assets/fonts/KaiGenGothicCN-Regular.ttf');
}
```
两个字体使用同一个字族名 `KaiGenGothic` 但是字重分别是 `bold` 与 `normal`。我另外声明
```
.cjk {
    font-family: 'Helvetica Neue', 'Helvetica', 'Avenir Next', 'Avenir', 'KaiGenGothic', 'Noto Sans CJK SC', 'Hiragino Sans GB', 'PingFang SC', 'Microsoft Yahei', sans-serif !important;
}
```
在有 CJK 文字时调用上述样式，但是个别部分，例如在其他的 `class` 中指定 `font-weight: bold;` Bold 字重将不能正常处理，在 Output 部分将会显示 Bold 字重无任何字符。对此我对使用 Bold 字重的地方重新覆盖了一项设定：
```
.cjk-bold {
    font-family: 'Helvetica Neue', 'Helvetica', 'Avenir Next', 'Avenir', 'KaiGenGothic', 'Noto Sans CJK SC', 'Hiragino Sans GB', 'PingFang SC', 'Microsoft Yahei', sans-serif !important;
    font-weight: bold;
}
```
这样才可以正常处理。
- 对 Font Awesome 处理出错  
我的网站上使用了 Font Awesome，大多数图标都可以正常显示，但是有一个 500px 的图标在处理之后，iPad 和 iPhone 将会显示为一个问号。只好在每次使用 font-spider 之后将处理后的替换为原始的 Font Awesome 图标。尚不清楚为什么会出现这种问题，但是我比较好奇是否能添加一种忽略条件为不处理小于特定大小的文件。毕竟 Font Awesome 也占用不了很多空间。

希望针对上述意见做出解答。

**Comment by aui** [comment]
字体继承带来的 font-weight 问题在解决中，`--ignore`的问题我检查下 

关于 Font Awesome：可以用 `--ignore` 来忽略 Font Awesome 文件

**Comment by starkshaw** [comment]
@aui Font Awesome 的字体文件有 6 个，所以我选择忽略 font-awesome.css 但是似乎没有作用。

**Comment by aui** [comment]
已经解决
