### ISSUE TITLE
The font no created

### ISSUE THREAD

**Issue by noonhorse** [aui/font-spider#53]
字体无法创建,情况如下。
![image](https://cloud.githubusercontent.com/assets/4952447/10189167/389009f2-6797-11e5-9af1-3541ab807876.png)

**Comment by songlipeng2003** [comment]
同样的问题，解决了吗？

**Comment by aui** [comment]
可能第一个字体文件有未知错误，这里有一份可以使用的思源黑体 ttf 版本：<https://github.com/aui/free-fonts/archive/KaiGenGothic-1.001-SimplifiedChinese.zip>

**Comment by songlipeng2003** [comment]
是的，你给的那份字体可以，网上下载的不行，我之前转宋体什么的也是可以的。谢谢
