### ISSUE TITLE
--ignore 排除字体有个bug

### ISSUE THREAD

**Issue by simplees** [aui/font-spider#58]
项目中引入了iconfont 和 思源字体，我想用--ignore排除掉iconfont文件。 但是在下面这种情况下，排除是不生效的。

    div:before{    
      content:'\e618';    
      font-family:iconfont;   
    }

特殊情况下需要将图标写到具体div的 `::before` 伪类中作为背景使用，这种情况下 即使排除了 `iconfont.*` 也会对iconfont进行编译，请问有什么办法能解决吗

**Comment by aui** [comment]
ignore 是基于路径的，你可以排除 iconfont 的文件名

**Comment by simplees** [comment]
应该怎么排除呢？ 还有一个问题： `font-spider *.html`好像会报错，只能针对单个或多个页面进行编译，nodejs版式是4.2.2。

**Comment by aui** [comment]
已经解决
