### ISSUE TITLE
Uses unrecognised table 'webf'

### ISSUE THREAD

**Issue by airyland** [aui/font-spider#6]
Dropping table 'FFTM'
Uses unrecognised table 'webf'

这报错是什么意思，能不能更友好易懂一些？

**Comment by aui** [comment]
这是内部错误，这意味着这个 ttf 文件不支持。目前支持较好的是方正字库等一些厂商制作的标准 ttf 文件，使用第三方工具处理的 ttf 可能会携带无法支持的数据。

新的版本正在尝试支持更多的格式。
