### ISSUE TITLE
css `font-weight` 可能导致遗漏字符

### ISSUE THREAD

**Issue by aui** [aui/font-spider#62]
``
h3 {font-weight: 800;}
``

**Comment by awesomes-cn** [comment]
同样 发现了这个Bug，设置 font-weight 后就识别不出来了，最终导致没压缩。

**Comment by awesomes-cn** [comment]
经测试，写到html标签里面是没问题的

**Comment by jkwchk** [comment]
想问现在这个问题有什么进展了吗？
刚压缩一个页面只有normal的字体正常出来了，其它同一font-family下的200， 500， 700等仅仅是生成了和原字体同样大小的相应格式。

**Comment by aztack** [comment]
```css
h1{font-weight:normal}
```
中的文字漏了
