### ISSUE TITLE
递归执行文件

### ISSUE THREAD

**Issue by a0x** [aui/font-spider#77]
我想把这套工具应用在我的静态博客中，遇到一个问题是：

博客按照`year/month/date/title/index.html`的路径生成HTML文件，当这种路径变得复杂时，目前非常难进行操作。

考虑到常见的Linux命令中都有`-r`参数表示递归执行，`font-spider`里加上这个参数会不会更好一些？

**Comment by aui** [comment]
命令行调用方式是支持 [glob](https://github.com/isaacs/node-glob) 的方式的，例如：

```
font-spider year/**/*.html
```
