### ISSUE TITLE
一个需求:强烈建议加入output参数,可以把处理后的字体文件放到其它地方

### ISSUE THREAD

**Issue by minzojian** [aui/font-spider#92]
RT
很感谢你们弄了这么个牛逼闪闪的项目
我在使用字蛛的时候,碰到这种需求
我有一个共享文件夹里放的全是各种字体,然后我的工程里用到那些字体中的一部分
我希望的是,我使用-map的方式,把网页上的字体和本地字体库做对比,再将用到的字体经处理后再放回到我自己的工程目录下,所以希望增加一个output参数
最后能这样使用
font-spider --map "http://mysite/fonts,c:\shareFonts" http://mysite --output c:\myproject\fonts

**Comment by aui** [comment]
感觉需求有点小众了。建议你使用 API 的方式调用字蛛: `fontSpider.spider()`，然后将得到的字符用 fontmin 压缩，这样可以任意定义目录
