### ISSUE TITLE
空白为什么会变宽

### ISSUE THREAD

**Issue by minzojian** [aui/font-spider#95]
为什么处理后字体的页面中的空白看起来要比实际的宽了一点呢?
看起来就象是空白变成了全角一样
![image](https://cloud.githubusercontent.com/assets/361781/15649849/384bd690-26a7-11e6-9b19-66c37c05dcef.png)
![image](https://cloud.githubusercontent.com/assets/361781/15649854/42dce1bc-26a7-11e6-8f10-d37d438fa9bd.png)

**Comment by ls84** [comment]
我这里处理过后字体里好像没有空格，而是被没有宽度的"!"代替了。

![fsn_j](https://cloud.githubusercontent.com/assets/7627744/17575833/566500d0-5f9f-11e6-8d66-1cf268505a8e.jpg)
![fso_j](https://cloud.githubusercontent.com/assets/7627744/17575832/56648f60-5f9f-11e6-9bca-253b70e279af.jpg)

我觉得压缩的时候没有包括这个“none breaking space”。试过用&nbsp;替代，仍然没有办法包含这个空格。
![fsc](https://cloud.githubusercontent.com/assets/7627744/17575952/a53d7f88-5fa0-11e6-967d-959f296d2d60.jpg)

我用的是英文系统的Mac OS 和英文的Safari。

**Comment by songlipeng2003** [comment]
同样的问题，所有空格会变成感叹号，求解决方案

**Comment by grass0916** [comment]
同，空格會變成驚嘆號 （！），使用字體 KaiGenGothicTC。

感覺也是壓縮後的字體檔並不包含 space 的 character。

**Comment by aui** [comment]
请更新版本，已经修复

**Comment by zbjy** [comment]
ie下空格还是会变成感叹号！

**Comment by jc91715** [comment]
最新版还是会有空格。。

**Comment by jc91715** [comment]
已解决 原来是中英文不能放在一起压缩

**Comment by RainKolwa** [comment]
@jc91715 请问你的空格变宽的问题解决了吗？不放在一起的意思是分开两个div存放中英文？

**Comment by piouswolf** [comment]
```
<div class="page-header">
      <div style="font-family:mihei_bold;">我 们</div>
      <div style="font-family:mihei_bold">A</div>
</div>

Include chars: A们我
Chars length: 3
```
空格被忽略了。
请问是哪里不对吗？
