### ISSUE TITLE
产品体验一塌糊涂

### ISSUE THREAD

**Issue by Mantak** [aui/font-spider#98]
首先，向您们的工作表示敬意，有了您们的劳动，互联网才变的更美好
然后，打脸
要求先设置CSS，后提供HTML，简单的问题复杂化。  其实产品需求很简单：

一个命令2个参数   font-spider XXX.ttf   XXXX.txt  
生成各种格式的字体文件。至于在css怎么引用，那是用户自己的事情咯

至于遍历html文件，真的不可取，
第一内容可能是数据库里提取的。文字的不确定性
第二特殊字体不可能用的太多
所以，还是要求提供个txt的文件，大家都省事

**Comment by toyjack** [comment]
简直不知所云，您这是打谁的脸？

**Comment by aui** [comment]
你适合 fontmin
